//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otelotomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odalar_kayit
    {
        public int kayit_id { get; set; }
        public string kayit_mus_tc { get; set; }
        public Nullable<int> kayit_oda_id { get; set; }
        public Nullable<System.DateTime> kayit_giris_tarih { get; set; }
        public Nullable<System.DateTime> kayit_cikis_tarih { get; set; }
        public Nullable<bool> kayit_gecerlilik { get; set; }
    
        public virtual odalar odalar { get; set; }
    }
}
