//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otelotomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public odalar()
        {
            this.odalar_kayit = new HashSet<odalar_kayit>();
        }
    
        public int oda_id { get; set; }
        public Nullable<short> oda_tip { get; set; }
        public Nullable<bool> oda_durum { get; set; }
        public Nullable<short> oda_ozellik { get; set; }
        public Nullable<int> oda_ucret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odalar_kayit> odalar_kayit { get; set; }
    }
}
