//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otelotomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class otel_log
    {
        public int islem_id { get; set; }
        public string islem_aciklama { get; set; }
        public string islem_yapan { get; set; }
        public Nullable<System.DateTime> islem_yapilan_zaman { get; set; }
    }
}
