//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otelotomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yetkili
    {
        public int u_id { get; set; }
        public string u_ad { get; set; }
        public string u_password { get; set; }
        public short u_yetki { get; set; }
        public Nullable<bool> u_gecerli { get; set; }
    
        public virtual yetkiler yetkiler { get; set; }
    }
}
